### ISSUE TITLE
Using vaadin-core (free) still wants a Pro licence

### ISSUE THREAD

**Issue by cfnz** [vaadin/base-starter-flow-portlet#38]
I am not sure where best to ask about this.

I want to create a Vaadin (if possible) portlet (I had a couple of version 7 portlets running on Liferay 6.x some time ago).

Looking at Liferay 7.x, it seems an OSGi portlet is a no go as it is part of the commercial Vaadin offering (which is not an option in this case). The documentation talked about using a non OSGi Portlet 3.0 alternative, so this is the track that led me here.

I have cloned this repo, and in the pom.xml changed the dependancy to vaadin-core as suggested by the comment:
```
 <!-- Replace artifactId with vaadin-core to use only free components -->
            <artifactId>vaadin</artifactId>
```
So I changed the above to vaadin-core, and managed to compile and deply to pluto, but it seems to still want to go off to Vaadin servers and validate my developer pro licence. I got a trial which solved the problem, for two weeks I am guessing.

So the behaviour seems to imply that, although the comment indicates you can use the Vaadin free version, in fact you can't.

Is this correct behaviour?

Thanks.

**Comment by mshabarov** [comment]
Hi @cfnz , thanks for the question!
Vaadin Portlet add-on requires Prime subscription. `vaadin-core` can be used if you don't want to use commercial components. Having `vaadin-core` reduces bundle size and improves build time.

**Comment by cfnz** [comment]
Thanks for the update, so just confirming the base-starter-flow-portlet (or any Vaadin portlet for that matter), can only be used with a Prime subscription (since the base-starter-flow-portlet uses the Vaadin portlet add on which needs a Prime subscription).

**Comment by cfnz** [comment]
It might also be worthwhile to delete the comment in line 76 of the pom which initially led me to believe that this would work with the Vaadin non Prime subscription.

The comment is: `<!-- Replace artifactId with vaadin-core to use only free components -->`
